'use client';

import React, { useState } from 'react';
import { supabase } from '@/lib/supabaseClient';
import { generateSlug } from '../utils/generateSlug'; 
import UrlShortener from './UrlShortener';
const LinkGenerator = () => {
    const [generatedLink, setGeneratedLink] = useState("");
    const [linkName, setLinkName] = useState("");
    const [loading, setLoading] = useState(false);
    const [copyStatus, setCopyStatus] = useState("Copy");

    const generateLink = async (e: React.MouseEvent<HTMLButtonElement>) => {
        e.preventDefault();
        
        if (!linkName.trim()) return alert("Please give your link a name (e.g. 'Insta Bio')");
        
        setLoading(true);

        try {
       
            const { data: userData, error: userError } = await supabase.auth.getUser();
            if (userError || !userData?.user) {
                throw new Error('You must be logged in.');
            }

           
            const newSlug = generateSlug(); 

           
            const { data, error: linkError } = await supabase
                .from('links')
                .insert({ 
                    creator_user_id: userData.user.id, 
                    name: linkName,
                    slug: newSlug
                    // 'id' (UUID) is auto-generated by Supabase default
                })
                .select()
                .single();


            if (linkError) throw linkError;

            // 4. Success! Show the Short Link
            // Note: It points to /m/[slug] now
            const shortUrl = `${window.location.origin}/m/${newSlug}`;
            setGeneratedLink(shortUrl);

                  const { error: historyError } = await supabase
            .from('linkhistory')
            .insert({ 
                content: shortUrl,
            
                creator_user_id: userData.user.id,
            });

        if (historyError) {
            console.error('Error inserting into linkhistory:', historyError);
            alert('Failed to save link history.');
            return;
        }

        } catch (err: any) {
            console.error('Creation Error:', err);
            alert(err.message);
        } finally {
            setLoading(false);
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(generatedLink);
        setCopyStatus("Copied!");
        setTimeout(() => setCopyStatus("Copy"), 2000);
    };

    return (
        <div className="w-full max-w-md mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
            
            {/* --- CARD CONTAINER --- */}
            <div className="bg-[#0a0a0a] border border-white/10 rounded-2xl p-6 shadow-2xl relative overflow-hidden">
                
                {/* Background Glow */}
                <div className="absolute top-0 right-0 -mr-10 -mt-10 w-32 h-32 bg-emerald-500/10 rounded-full blur-[50px]"></div>

                <div className="relative z-10">
                    <h2 className="text-xl font-bold text-white mb-1">Create Secure Link</h2>
                    <p className="text-xs text-gray-500 mb-6">Generate a traceable, anonymous entry point.</p>
                    
                    {/* INPUT FIELD */}
                    <div className="space-y-2 mb-6">
                        <label className="text-[10px] font-mono text-emerald-500 uppercase tracking-widest">Link Alias</label>
                        <input 
                            type="text" 
                            onChange={(e) => setLinkName(e.target.value)} 
                            value={linkName}
                            placeholder="e.g. Instagram Story, TikTok Bio..."
                            className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-600 focus:outline-none focus:border-emerald-500/50 focus:bg-black/60 transition-all"
                        />
                    </div>

                    {/* GENERATE BUTTON */}
                    <button 
                        onClick={generateLink} 
                        disabled={loading}
                        className="w-full py-3.5 bg-gradient-to-r from-emerald-600 to-teal-600 rounded-xl font-bold text-black hover:shadow-[0_0_20px_rgba(16,185,129,0.4)] transition-all active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                    >
                        {loading ? (
                            <>
                                <div className="w-4 h-4 border-2 border-black/30 border-t-black rounded-full animate-spin"></div>
                                <span>Encrypting...</span>
                            </>
                        ) : (
                            <>
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1"></path></svg>
                                Generate Link
                            </>
                        )}
                    </button>

                    {/* RESULT SECTION */}
                    {generatedLink && (
                        <div className="mt-8 pt-6 border-t border-white/10 animate-in zoom-in-95 duration-300">
                            <div className="flex items-center justify-between mb-2">
                                <label className="text-[10px] font-mono uppercase tracking-widest text-emerald-400">
                                    // Link Active
                                </label>
                            </div>

                            <div className="relative flex items-center bg-black/60 border border-emerald-500/30 rounded-xl p-1 pl-3">
                                <input
                                    type="text"
                                    value={generatedLink}
                                    readOnly
                                    className="w-full bg-transparent text-sm font-mono text-gray-300 outline-none truncate"
                                />
                                <button 
                                    onClick={handleCopy} 
                                    className={`ml-2 px-4 py-2 rounded-lg text-xs font-bold transition-all shrink-0 flex items-center gap-2 ${
                                        copyStatus === "Copied!" 
                                        ? "bg-emerald-500 text-black" 
                                        : "bg-white/10 text-white hover:bg-white/20"
                                    }`}
                                >
                                    {copyStatus}
                                    {copyStatus === "Copy" && <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"></path></svg>}
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            </div>
            <br /><br />
            <UrlShortener/>
        </div>
    );
};

export default LinkGenerator;